import Head from 'next/head'
// import Image from 'next/image'
// Importing components here //

import Hero from '../components/Hero'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Apolloz Fotografi AB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Captur Photography' message='Capture everything'/>
    </div>
  )
}
